# Generated by Django 5.2.3 on 2025-06-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_contable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='ruc_cedula',
            new_name='cedula',
        ),
    ]
