# Generated by Django 5.2.3 on 2025-06-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_contable', '0002_rename_ruc_cedula_client_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
