# Generated by Django 5.2.3 on 2025-08-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_contable', '0004_purchase_supplier_inventorymovement_inventoryproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='type',
            field=models.CharField(choices=[('increase', 'Incremento'), ('decrease', 'Decremento'), ('purchase', 'Compra'), ('sale', 'Venta')], max_length=20),
        ),
    ]
