# Generated by Django 5.2.3 on 2025-08-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_contable', '0005_alter_inventorymovement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
