# Generated by Django 5.2.3 on 2025-09-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_contable', '0008_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('sent', 'Enviada'), ('paid', 'Pagada'), ('overdue', 'Vencida')], max_length=10),
        ),
    ]
